# Generated by Django 2.2.3 on 2019-08-12 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dance', 'Dance'), ('Dramatics', 'Dramatics'), ('Fine Arts', 'Fine Arts'), ('Gaming', 'Gaming'), ('Life Style', 'Life Style'), ('Literary', 'Literary'), ('Music', 'Music'), ('Photography', 'Photography'), ('Quizzing', 'Quizzing'), ('Video Making', 'Video Making')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('event_type', models.CharField(choices=[('Solo', 'Solo'), ('Duet', 'Duet'), ('Group', 'Group')], max_length=5)),
                ('first_cash_prize', models.IntegerField()),
                ('second_cash_prize', models.IntegerField()),
                ('third_cash_prize', models.IntegerField()),
                ('minimum_team_size', models.IntegerField()),
                ('maximum_team_size', models.IntegerField()),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('link_to_rulebook', models.URLField(max_length=400, verbose_name='Link to Rulebook')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participating_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('participant_code', models.CharField(max_length=15, verbose_name='Participant Code')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('primary_mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Primary Mobile Number')),
                ('secondary_mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Secondary Mobile Number')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TeamHasMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Team')),
            ],
            options={
                'verbose_name_plural': 'Team Has Member',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('participation_fees_per_person', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='ParticipantHasParticipated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
            ],
            options={
                'verbose_name_plural': 'Participant Has Participated',
            },
        ),
        migrations.CreateModel(
            name='ParticipantHasPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='-1', max_length=100)),
                ('paid_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.SubCategory')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
            ],
            options={
                'verbose_name_plural': 'Participant Has Paid',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.SubCategory'),
        ),
    ]
