# Generated by Django 2.2.3 on 2019-08-10 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DC', 'Dance'), ('DM', 'Dramatics'), ('FA', 'Fine Arts'), ('GM', 'Gaming'), ('LS', 'Life Style'), ('LT', 'Literary'), ('MS', 'Music'), ('PH', 'Photography'), ('QZ', 'Quizzing'), ('VM', 'Video Making')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('event_type', models.CharField(choices=[('SL', 'Solo'), ('DT', 'Duet'), ('GP', 'Group')], max_length=2)),
                ('first_cash_prize', models.IntegerField()),
                ('second_cash_prize', models.IntegerField()),
                ('third_cash_prize', models.IntegerField()),
                ('minimum_team_size', models.IntegerField()),
                ('maximum_team_size', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Mobile Number')),
                ('participating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('primary_mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Primary Mobile Number')),
                ('secondary_mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Secondary Mobile Number')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TeamHasMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Team')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('participation_fees_per_person', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantHasParticipated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantHasPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.SubCategory')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.SubCategory'),
        ),
    ]
