# Generated by Django 2.2.3 on 2021-02-12 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus_ambassador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dance', 'Dance'), ('Dramatics', 'Dramatics'), ('Fine Arts', 'Fine Arts'), ('Gaming', 'Gaming'), ('Life Style', 'Life Style'), ('Literary', 'Literary'), ('Music', 'Music'), ('Photography', 'Photography'), ('Quizzing', 'Quizzing'), ('Video Making', 'Video Making')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('link_to_rulebook', models.URLField(max_length=300)),
                ('participation_fees_per_person', models.IntegerField()),
                ('event_type', models.CharField(choices=[('Solo', 'Solo'), ('Group', 'Group')], max_length=5)),
                ('first_cash_prize', models.IntegerField()),
                ('second_cash_prize', models.IntegerField()),
                ('third_cash_prize', models.IntegerField()),
                ('first_goodies', models.IntegerField()),
                ('second_goodies', models.IntegerField()),
                ('third_goodies', models.IntegerField()),
                ('minimum_team_size', models.IntegerField()),
                ('maximum_team_size', models.IntegerField()),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_photo_in_static_files', models.CharField(max_length=15)),
                ('link_to_sponsor', models.URLField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Our Sponsor',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participating_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Participating User')),
                ('participant_code', models.CharField(max_length=15, unique=True, verbose_name='Participant Code')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('college_name', models.CharField(max_length=200, verbose_name='College Name')),
                ('college_city', models.CharField(max_length=50, verbose_name='College City')),
                ('personal_address_with_pin_code', models.TextField(verbose_name='Personal Address with PIN Code')),
                ('contact_mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Contact Mobile Number')),
                ('whatsapp_mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='WhatsApp Mobile Number')),
                ('birth_date', models.DateField(verbose_name='Birth Date (YYYY-MM-DD)')),
                ('referring_ca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus_ambassador.RegistrationDetails', verbose_name='CA Referral Code')),
            ],
        ),
        migrations.CreateModel(
            name='Prev_Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_photo_in_static_files', models.CharField(max_length=15)),
                ('link_to_sponsor', models.URLField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Previous Sponsor',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Team Name')),
                ('team_code', models.CharField(max_length=50, unique=True, verbose_name='Team Code')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TeamHasMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Team')),
            ],
            options={
                'verbose_name_plural': 'Team Has Member',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.CharField(max_length=10)),
                ('transaction_id', models.CharField(default='-1', max_length=100)),
                ('payment_request_id', models.CharField(default='-1', max_length=100)),
                ('donating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='ParticipantHasParticipated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
            ],
            options={
                'verbose_name_plural': 'Participant Has Participated',
            },
        ),
        migrations.CreateModel(
            name='ParticipantHasPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='-1', max_length=100)),
                ('payment_request_id', models.CharField(default='-1', max_length=100)),
                ('paid_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant')),
            ],
            options={
                'verbose_name_plural': 'Participant Has Paid',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Subcategory'),
        ),
    ]
