# Generated by Django 2.2.3 on 2019-08-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='primary_mobile_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='secondary_mobile_number',
        ),
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(default=20, max_length=15, unique=True, verbose_name='Team Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Participant Code'),
        ),
    ]
