# Generated by Django 2.2.3 on 2021-03-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_photo_in_static_files', models.CharField(max_length=15)),
                ('link_to_sponsor', models.URLField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Media Partner',
            },
        ),
    ]
