# Generated by Django 2.2.3 on 2019-08-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamHasMembers',
            new_name='TeamHasMember',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='participanthaspaid',
            options={'verbose_name_plural': 'Participant Has Paid'},
        ),
        migrations.AlterModelOptions(
            name='participanthasparticipated',
            options={'verbose_name_plural': 'Participant Has Participated'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='teamhasmember',
            options={'verbose_name_plural': 'Team Has Member'},
        ),
    ]
