# Generated by Django 2.2.3 on 2019-08-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20190820_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='college',
            field=models.CharField(default='no college', max_length=200, verbose_name='College Name'),
            preserve_default=False,
        ),
    ]
