# Generated by Django 2.2.3 on 2019-08-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20190811_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Dance', 'Dance'), ('Dramatics', 'Dramatics'), ('Fine Arts', 'Fine Arts'), ('Gaming', 'Gaming'), ('Life Style', 'Life Style'), ('Literary', 'Literary'), ('Music', 'Music'), ('Photography', 'Photography'), ('Quizzing', 'Quizzing'), ('Video Making', 'Video Making')], max_length=20),
        ),
    ]
