# Generated by Django 2.2.3 on 2021-03-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_media_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Website Counts',
            },
        ),
    ]
