# Generated by Django 2.2.3 on 2019-08-22 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_participant_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participating_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Participating User'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Team Name'),
        ),
    ]
