# Generated by Django 2.2.3 on 2021-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_webcounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tech', 'Tech'), ('Cult', 'Cult')], max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('code', models.IntegerField(unique=True)),
                ('event_type', models.CharField(choices=[('Solo', 'Solo'), ('Group', 'Group')], max_length=5)),
                ('rulebook', models.URLField(max_length=300)),
            ],
        ),
    ]
