# Generated by Django 2.2.3 on 2021-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_webcounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Our Team',
            },
        ),
    ]
