# Generated by Django 2.2.3 on 2019-08-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20190822_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(default='no_name', max_length=40, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
