# Generated by Django 2.2.3 on 2021-03-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events List'},
        ),
    ]
