# Generated by Django 2.2.3 on 2019-08-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20190811_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('DANCE', 'DANCE'), ('DRAMATICS', 'DRAMATICS'), ('FINE_ARTS', 'FINE_ARTS'), ('GAMING', 'GAMING'), ('LIFE_STYLE', 'LIFE_STYLE'), ('LITERARY', 'LITERARY'), ('MUSIC', 'MUSIC'), ('PHOTOGRAPHY', 'PHOTOGRAPHY'), ('QUIZZING', 'QUIZZING'), ('VIDEO_MAKING', 'VIDEO_MAKING')], max_length=20),
        ),
    ]
