# Generated by Django 2.2.3 on 2019-08-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='first_goodies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='second_goodies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='third_goodies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
