# Generated by Django 2.2.3 on 2019-08-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20190811_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Duet', 'Duet'), ('Group', 'Group')], max_length=5),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('Dance', 'Dance'), ('Dramatics', 'Dramatics'), ('Fine Arts', 'Fine Arts'), ('Gaming', 'Gaming'), ('Life Style', 'Life Style'), ('Literary', 'Literary'), ('Music', 'Music'), ('Photography', 'Photography'), ('Quizzing', 'Quizzing'), ('Video Making', 'Video Making')], max_length=20),
        ),
    ]
