# Generated by Django 2.2.3 on 2021-04-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_registrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
