# Generated by Django 2.2.3 on 2021-03-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20210321_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
