# Generated by Django 2.2.3 on 2019-08-24 10:57

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20190824_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='college',
            new_name='college_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='participant',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='college_city',
            field=models.CharField(default='K', max_length=50, verbose_name='College City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='contact_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+918282828282', max_length=128, region='IN', verbose_name='Contact Mobile Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='personal_address_with_pin_code',
            field=models.CharField(default='k', max_length=200, verbose_name='Personal Address with PIN Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='whatsapp_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+918282828282', max_length=128, region='IN', verbose_name='WhatsApp Mobile Number'),
            preserve_default=False,
        ),
    ]
