# Generated by Django 2.2.3 on 2019-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20190811_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanthaspaid',
            name='transaction_id',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
    ]
