# Generated by Django 2.2.3 on 2021-03-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_auto_20210321_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.CharField(choices=[('tech', 'tech'), ('cult', 'cult')], max_length=20),
        ),
    ]
