# Generated by Django 2.2.3 on 2019-08-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20190824_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='link_to_rulebook',
        ),
        migrations.AlterField(
            model_name='participant',
            name='birth_date',
            field=models.DateField(verbose_name='Birth Date (YYYY-MM-DD)'),
        ),
    ]
