# Generated by Django 2.2.3 on 2021-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_clubs_event_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_partner',
            name='name_of_photo_in_static_files',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='our_sponsor',
            name='name_of_photo_in_static_files',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prev_sponsor',
            name='name_of_photo_in_static_files',
            field=models.CharField(max_length=50),
        ),
    ]
