# Generated by Django 2.2.3 on 2019-08-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_participanthaspaid_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanthaspaid',
            name='transaction_id',
            field=models.CharField(default='-1', max_length=100),
        ),
    ]
