# Generated by Django 2.2.3 on 2021-03-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20210321_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='rulebook',
            field=models.CharField(max_length=300),
        ),
    ]
