# Generated by Django 2.2.3 on 2021-04-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20210408_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashlessReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cashless Registrations',
            },
        ),
    ]
