# Generated by Django 2.2.3 on 2019-08-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20190824_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='personal_address_with_pin_code',
            field=models.TextField(verbose_name='Personal Address with PIN Code'),
        ),
    ]
