# Generated by Django 2.2.3 on 2021-04-11 15:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_cashlessreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashlessreg',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
    ]
