# Generated by Django 2.2.3 on 2019-08-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20190824_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Team Code'),
        ),
    ]
