# Generated by Django 2.2.3 on 2021-03-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='events',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
