# Generated by Django 2.2.3 on 2019-08-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_auto_20190825_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_photo_in_static_files', models.CharField(max_length=15)),
                ('link_to_sponsor', models.URLField(max_length=300)),
            ],
        ),
    ]
