# Generated by Django 2.2.3 on 2021-03-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_registration_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
    ]
