# Generated by Django 2.2.3 on 2021-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_auto_20210411_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='events',
            field=models.CharField(max_length=50000),
        ),
    ]
