# Generated by Django 2.2.3 on 2021-03-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_remove_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='events',
            field=models.CharField(max_length=500),
        ),
    ]
