# Generated by Django 2.2.3 on 2019-08-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_roomregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomregistration',
            options={'verbose_name_plural': 'Room Registrations'},
        ),
        migrations.AlterField(
            model_name='roomregistration',
            name='aadhar_no',
            field=models.IntegerField(verbose_name='12-digit Aadhar No.'),
        ),
        migrations.AlterField(
            model_name='roomregistration',
            name='no_days',
            field=models.CharField(choices=[('ONE', '1 day'), ('TWO', '2 days'), ('THREE', '3 days')], max_length=10, verbose_name='No. of days'),
        ),
    ]
