# Generated by Django 2.2.3 on 2021-04-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_auto_20210417_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_partner',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='our_sponsor',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prev_sponsor',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
