# Generated by Django 2.2.3 on 2019-08-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_auto_20190825_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomregistration',
            old_name='occupant',
            new_name='participant',
        ),
    ]
