# Generated by Django 2.2.3 on 2019-08-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_accomodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=4, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
