# Generated by Django 2.2.3 on 2021-04-21 19:02

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_auto_20210421_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('ss', models.ImageField(blank=True, null=True, upload_to='feedback_uploads/', validators=[main_page.models.validate_file_size])),
                ('feedback', models.TextField(blank=True, max_length=5000, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
