# Generated by Django 2.2.3 on 2021-03-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_auto_20210322_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='mobile',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='user_unique_id',
            field=models.CharField(default=999, max_length=200),
            preserve_default=False,
        ),
    ]
