# Generated by Django 2.2.3 on 2021-03-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_auto_20210322_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='sub_category',
            field=models.CharField(default='a', max_length=40),
            preserve_default=False,
        ),
    ]
