# Generated by Django 2.2.3 on 2019-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_accomodation_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='no_days',
        ),
        migrations.AddField(
            model_name='accomodation',
            name='no_of_days',
            field=models.CharField(choices=[('1', '1 DAY'), ('2', '2 DAYS'), ('3', '3 DAYS')], default='1 DAY', max_length=10, verbose_name='Number of days'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='aadhar_no',
            field=models.CharField(max_length=4, verbose_name='Last 4 digits of your Aadhar Number'),
        ),
    ]
