# Generated by Django 2.2.3 on 2019-08-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_auto_20190825_1022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomRegistration',
            new_name='Accomodation',
        ),
        migrations.AlterModelOptions(
            name='accomodation',
            options={'verbose_name_plural': 'Accomodation'},
        ),
    ]
