# Generated by Django 2.2.3 on 2021-03-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_events_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.RemoveField(
            model_name='events',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Cat'),
        ),
    ]
