# Generated by Django 2.2.3 on 2021-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_ongoingevents_upcomingevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingevents',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ongoingevents',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingevents',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upcomingevents',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
