# Generated by Django 2.2.3 on 2021-03-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_auto_20210323_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='category',
            new_name='cat',
        ),
    ]
