# Generated by Django 2.2.3 on 2019-08-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_auto_20190825_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_photo_in_static_files', models.CharField(max_length=15)),
                ('link_to_sponsor', models.URLField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='aadhar_no',
            field=models.CharField(max_length=4, verbose_name='Last 4 digits of Aadhar No.'),
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='no_days',
            field=models.CharField(choices=[('ONE', '1 day'), ('TWO', '2 days'), ('THREE', '3 days')], max_length=10, verbose_name='Number of days'),
        ),
    ]
