# Generated by Django 2.2.3 on 2021-04-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_auto_20210422_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevents',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
