# Generated by Django 2.2.3 on 2021-03-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_auto_20210323_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='cat',
        ),
        migrations.AddField(
            model_name='events',
            name='cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Cat'),
        ),
    ]
