# Generated by Django 2.2.3 on 2019-09-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_auto_20190917_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prev_Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_photo_in_static_files', models.CharField(max_length=15)),
                ('link_to_sponsor', models.URLField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='Sponsor',
            new_name='Our_Sponsor',
        ),
    ]
