# Generated by Django 2.2.3 on 2019-09-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_auto_20190922_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='our_sponsor',
            options={'verbose_name_plural': 'Our Sponsor'},
        ),
        migrations.AlterModelOptions(
            name='prev_sponsor',
            options={'verbose_name_plural': 'Previous Sponsor'},
        ),
    ]
