# Generated by Django 2.2.3 on 2021-03-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_auto_20210323_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='cate',
        ),
    ]
