# Generated by Django 2.2.3 on 2021-03-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_events_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Event Sub Categories',
            },
        ),
        migrations.RemoveField(
            model_name='cat',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='events',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.SubCat'),
        ),
        migrations.AddField(
            model_name='subcat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.Cat'),
        ),
    ]
