# Generated by Django 2.2.3 on 2019-10-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_auto_20191001_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='include_meals',
            field=models.BooleanField(default=False, verbose_name='Meals Included'),
        ),
    ]
