# Generated by Django 2.2.3 on 2019-10-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_accomodation_include_meals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accomodation',
        ),
    ]
