# Generated by Django 2.2.3 on 2019-10-01 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0020_accomodation_include_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant', verbose_name='Participant'),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.CharField(max_length=10)),
                ('transaction_id', models.CharField(default='-1', max_length=100)),
                ('payment_request_id', models.CharField(default='-1', max_length=100)),
                ('donating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
