# Generated by Django 2.2.3 on 2021-03-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0020_auto_20210323_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
    ]
