# Generated by Django 2.2.3 on 2019-10-02 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0021_delete_accomodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_amount', models.CharField(max_length=10)),
                ('transaction_id', models.CharField(default='-1', max_length=100)),
                ('payment_request_id', models.CharField(default='-1', max_length=100)),
                ('donating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acco_for_day_one', models.BooleanField(default=False, verbose_name='11 Oct')),
                ('acco_for_day_two', models.BooleanField(default=False, verbose_name='12 Oct')),
                ('acco_for_day_three', models.BooleanField(default=False, verbose_name='13 Oct')),
                ('include_meals', models.BooleanField(default=False, verbose_name='Meals Included')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=4, verbose_name='Gender')),
                ('transaction_id', models.CharField(default='-1', max_length=100)),
                ('payment_request_id', models.CharField(default='-1', max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.Participant', verbose_name='Participant')),
            ],
            options={
                'verbose_name_plural': 'Accomodation',
            },
        ),
    ]
