# Generated by Django 2.2.3 on 2021-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0022_events_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='poster',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='serial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
