# Generated by Django 2.2.3 on 2019-10-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='TBD', max_length=100),
            preserve_default=False,
        ),
    ]
