# Generated by Django 2.2.3 on 2021-02-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0024_event_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accomodation',
        ),
    ]
