# Generated by Django 2.2.3 on 2021-02-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_delete_accomodation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participanthaspaid',
            name='paid_subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='participation_fees_per_person',
        ),
        migrations.AddField(
            model_name='event',
            name='participation_fees_per_person',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participanthaspaid',
            name='paid_event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_page.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Group', 'Group')], max_length=5),
        ),
    ]
