# Generated by Django 2.2.3 on 2021-02-12 07:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TSPResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advitiya_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('marks', models.SmallIntegerField()),
                ('rank', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150)),
                ('point_of_contact_name', models.CharField(max_length=50)),
                ('school_phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('point_of_contact_phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('school_address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TSP_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_a', models.PositiveSmallIntegerField(verbose_name='No. of Students in Category A (Classes 9th & 10th)')),
                ('category_b', models.PositiveSmallIntegerField(verbose_name='No. of Students in Category B (Classes 11th & 12th)')),
                ('payment_request_id', models.CharField(default='none', max_length=100)),
                ('transaction_id', models.CharField(default='none', max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSP.Profile')),
            ],
        ),
    ]
