# Generated by Django 2.2.6 on 2019-10-31 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TSP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tec_head',
            new_name='point_of_contact_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='point_of_contact_phone',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='past_exp',
            new_name='school_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='college_name',
            new_name='school_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tec_head_phone',
            new_name='school_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ca_code',
        ),
    ]
