# Generated by Django 2.2.6 on 2019-12-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSP', '0002_auto_20191031_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_a', models.PositiveSmallIntegerField(verbose_name='Category A')),
                ('category_b', models.PositiveSmallIntegerField(verbose_name='Category B')),
                ('payment_request_id', models.CharField(default='none', max_length=100)),
                ('transaction_id', models.CharField(default='none', max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSP.Profile')),
            ],
        ),
    ]
