# Generated by Django 2.2.6 on 2019-12-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSP', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='category_a',
            field=models.PositiveSmallIntegerField(verbose_name='Category A(9-10th class)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='category_b',
            field=models.PositiveSmallIntegerField(verbose_name='Category B(11-12th class)'),
        ),
    ]
