# Generated by Django 2.2.6 on 2019-12-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSP', '0004_auto_20191203_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='category_a',
            field=models.PositiveSmallIntegerField(verbose_name='Category A (9-10th class)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='category_b',
            field=models.PositiveSmallIntegerField(verbose_name='Category B (11-12th class)'),
        ),
    ]
