# Generated by Django 2.2.6 on 2019-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSP', '0005_auto_20191203_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='category_a',
            field=models.PositiveSmallIntegerField(verbose_name='No. of Students in Category A (Classes 9th & 10th)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='category_b',
            field=models.PositiveSmallIntegerField(verbose_name='No. of Students in Category B (Classes 11th & 12th)'),
        ),
    ]
