# Generated by Django 2.2.6 on 2020-02-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSP', '0007_tspresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tspresult',
            name='marks',
            field=models.SmallIntegerField(),
        ),
    ]
