# Generated by Django 2.2.3 on 2019-08-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetails',
            name='campus_ambassador_code',
            field=models.CharField(max_length=15, unique=True, verbose_name='CA Code'),
        ),
    ]
