# Generated by Django 2.2.3 on 2019-07-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdetails',
            name='accept_campus_ambassador_policy',
        ),
        migrations.AlterField(
            model_name='registrationdetails',
            name='college',
            field=models.CharField(max_length=200, verbose_name='College Name'),
        ),
        migrations.AlterField(
            model_name='registrationdetails',
            name='mobile_number',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='registrationdetails',
            name='past_experience',
            field=models.TextField(verbose_name='Do you have any past experience related to this? If yes, then please share your experience'),
        ),
        migrations.AlterField(
            model_name='registrationdetails',
            name='why_interested',
            field=models.TextField(verbose_name='Why do you want to be a Campus Ambassador?'),
        ),
    ]
