# Generated by Django 2.2.3 on 2019-07-15 14:50

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0002_auto_20190712_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetails',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Mobile Number'),
        ),
    ]
