# Generated by Django 2.2.3 on 2019-07-15 14:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0003_auto_20190715_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetails',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Mobile Number'),
        ),
    ]
