# Generated by Django 2.2.3 on 2019-07-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0004_auto_20190715_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdetails',
            name='campus_ambassador_code',
            field=models.CharField(default='anything', max_length=15, verbose_name='CA code'),
            preserve_default=False,
        ),
    ]
