# Generated by Django 2.2.3 on 2019-08-22 18:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campus_ambassador', '0005_registrationdetails_campus_ambassador_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdetails',
            name='campus_ambassador_code',
            field=models.CharField(max_length=15, unique=True, verbose_name='CA code'),
        ),
        migrations.AlterField(
            model_name='registrationdetails',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Mobile Number'),
        ),
    ]
